theme: jekyll-theme-minimal
title: Golang and Kafka Unificated
description: Integrate golang with kafka in a simple and fast way, being able to choose the provider you want.
logo: https://user-images.githubusercontent.com/3587262/93725383-349abe00-fb85-11ea-988d-0adf332929c3.jpg
show_downloads: true
google_analytics: [Your Google Analytics tracking ID]
