global:
    scrape_interval:     1000ms
    evaluation_interval: 1000ms
    external_labels:
      monitor: 'goku'
rule_files:
  - "alert.rules_nodes"
  - "alert.rules_tasks"
  - "alert.rules_service-groups"
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - localhost:9090
  - job_name: kafka-exporter
    static_configs:
      - targets:
          - "kafka-exporter:9308"
  - job_name: kafka
    static_configs:
      - targets:
          - "kafka:7072"
  - job_name: goku
    static_configs:
    - targets:
      - host.docker.internal:8080          